config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => "127.0.0.1:3000"
  resources :posts do
    resources :comments
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  validates_presence_of :post
  has_rich_text :content
end

app/models/post.rb
class Post < ApplicationRecord
  has_rich_text :description
  validates_presence_of :post_name
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :get_post
  before_action :set_comment, only: %i[ show edit update destroy ]

  # GET /comments or /comments.json
  def index
    @comments = @post.comments
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = @post.comments.build
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @comment = @post.comments.build(comment_params)

    respond_to do |format|
      if @comment.save
        CommentsMailer.submitted(@comment).deliver_now
        format.html { redirect_to post_comments_path(@post), notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to post_comment_path(@post), notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy!

    respond_to do |format|
      format.html { redirect_to post_comments_path(@post), notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  def get_post
    @post = Post.find(params[:post_id])
  end
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = @post.comments.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:post_id, :content)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:post_name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag rails_representation_url(blob), width: 600, height: 800, :id => blob.try(:caption),
        onload: "getModal('#{ blob.try(:caption) }', 'modalist', 'caption', 'img01', 'close', 'full-size')", class: "transition",
        alt: "#{ blob.try(:caption) }", type: "#{ blob.content_type }", :only_path => true %>

    <div id="modalist" class="modal">

      <div class="container">

        <!-- The Close Button -->
        <span class="close">&times;</span>

        <a id="full-size" href="" target="_blank">

          <!-- Modal Content (The Image) -->
          <img class="modal-content" id="img01" alt="<%= blob.try(:caption) %>" src="" >

          <!-- Modal Caption (Image Text) -->
          <div id="caption"></div>

        </a>

      </div>

    </div>

  <% end %>

  <script>
        function getModal(id, modalId, captionId, imgId, closeClass, linkId) {
            // Get the modal
            let modal = document.getElementById(modalId);

            // Get the image and insert it inside the modal - use its "alt" text as a caption
            let img = document.getElementById(id);
            let modalImg = document.getElementById(imgId);
            let captionText = document.getElementById(captionId);
            let linkImg = document.getElementById(linkId);
            img.onclick = function () {
                linkImg.href = this.src;
                modal.style.display = "block";
                modalImg.src = this.src;
                captionText.innerHTML = this.alt;
            }

            // Get the <span> element that closes the modal
            let span = document.getElementsByClassName(closeClass)[0];

            // When the user clicks on <span> (x), close the modal
            span.onclick = function () {
                modal.style.display = "none";
            }
        }
    </script>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">

  <p>
    <strong>Content:</strong>
    <%= comment.content %>
  </p>

</div>

app/views/comments/_form.html.erb
<%= form_with(model: [@post, comment]) do |form| %>
  <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <strong>Post reference:</strong>
    <%= @post.post_name %>
  </p>

  <p>
    <strong>Post description:</strong>
    <%= @post.description %>
  </p>

  <div>
    <strong>Let your comment:</strong>
    <%= form.rich_text_area :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", [@post, @comment] %> |
  <%= link_to "Back to comments", post_comments_path(@post) %>
</div>

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Comments</h1>

<p>
  <strong>Post reference:</strong>
  <%= @post.post_name %>
</p>

<p>
  <strong>Post description:</strong>
  <%= @post.description %>
</p>

<div id="comments">
  <% @comments.each do |comment| %>
    <%= render comment %>
    <p>
      <%= link_to "Show this comment", [@post, comment] %>
    </p>
  <% end %>
</div>

<div>
  <%= link_to "Add Comment", new_post_comment_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Back to comments", post_comments_path(@post) %>
</div>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<div>
  <h2>Detailed comment about this Post</h2>

  <p>
    <%= @comment.content %>
  </p>

  <p>
    <strong>Last created:</strong>
    <%= time_tag @comment.created_at, "data-local": "time-ago" %>
  </p>
</div>

<div>
  <%= link_to "Edit this comment", edit_post_comment_path(@post) %> |
  <%= link_to "Back to comments", post_comments_path(@post) %>

  <%= button_to "Destroy this comment", [@post, @comment], method: :delete %>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='en'>
  <head>
    <title>SketBlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "https://cdn.simplecss.org/simple-v1.css" %>
    <%= stylesheet_link_tag "zoom.css" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :post_name, style: "display: block" %>
    <%= form.text_field :post_name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.rich_text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <p>
    <strong>Post name:</strong>
    <%= post.post_name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= post.description %>
  </p>

  <p>
    <strong>Posted:</strong>
    <%= time_tag post.created_at, "data-local": "time-ago" %>
  </p>

  <p>
    <strong>Comments:</strong>

    <%= link_to (pluralize post.comments.count, "comment"), post_comments_path(post) %>
  </p>

</div>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %> |
      <%= link_to "Comment this post", new_post_comment_path(post) %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>